version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8000:8000
    environment:
      API_KEY: ${API_KEY}
      API_SECRET_KEY: ${API_SECRET_KEY}
      ADMIN_API_TOKEN: ${ADMIN_API_TOKEN}
      SHOP: ${SHOP}
    command:  php -S 0.0.0.0:8000 -t app/public